package com.okmich.mysql2mongodb.ui;

import javax.swing.*;
import java.awt.*;
import javax.swing.JFrame;
import com.okmich.mysql2mongodb.ui.UserPanel;

public class AppFrame extends JFrame {


    private JPanel mainFrame;
    private JTabbedPane tabbedPane1;

    public AppFrame(String dbServerUrl, String dbUser, String dbPassword,
                    String mongoDbUrl, String mongoDbName) {
        $$$setupUI$$$();
        setSize(300, 300);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null); // Центрируем окно на экране
        tabbedPane1.addTab("Movies", new MoviePanel(dbServerUrl, dbUser, dbPassword, mongoDbUrl, mongoDbName).$$$getRootComponent$$$());
        tabbedPane1.addTab("Rating", new RatingPanel(dbServerUrl, dbUser, dbPassword, mongoDbUrl, mongoDbName).$$$getRootComponent$$$());
        tabbedPane1.addTab("Tags", new TagsPanel(dbServerUrl, dbUser, dbPassword, mongoDbUrl, mongoDbName).$$$getRootComponent$$$());
        tabbedPane1.addTab("Users", new UserPanel(dbServerUrl, dbUser, dbPassword, mongoDbUrl, mongoDbName).$$$getRootComponent$$$());

        add($$$getRootComponent$$$());


    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainFrame = new JPanel();
        mainFrame.setLayout(new BorderLayout(0, 0));
        tabbedPane1 = new JTabbedPane();
        mainFrame.add(tabbedPane1, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainFrame;
    }


}
